### ISSUE TITLE
R1 unclear

### ISSUE THREAD

**Issue by muralidn** [liziscool/cas741_project#18]
@liziscool 

![image](https://user-images.githubusercontent.com/71282513/95914392-4443a600-0dc3-11eb-9c76-7f3f60e51f75.png)

Please explain the context of  "analyzed as input". Does it mean signals should be analyzed after input, or signal should be considered an input? If it is the former, it should be a separate requirement.  The same goes for defaults in the second sentence.

**Comment by smiths** [comment]
@liziscool, when you close an issue, please give an explanation of why it was closed.  If the issue just requires some explanation, you can provide the explanation as a comment.  If closing the issue involves making changes to the SRS, then you should include the commit hash where those changes were made.
