### ISSUE TITLE
Please review VnV Plan

### ISSUE THREAD

**Issue by liziscool** [liziscool/cas741_project#26]
Hi @smiths,

Please review my VnV Plan document when you get a chance, it can be found here: https://github.com/liziscool/cas741_project/blob/master/docs/VnVPlan/VnVPlan.pdf
Thank you.

**Comment by smiths** [comment]
Spelling corrections are made in cb41aa8.

**Comment by smiths** [comment]
The review of the VnV Plan is given in 0e23c3c.
