### ISSUE TITLE
Please review SRS

### ISSUE THREAD

**Issue by liziscool** [liziscool/cas741_project#3]
Hi @smiths, 

My SRS can be found here: https://github.com/liziscool/cas741_project/blob/master/docs/SRS/SRS.pdf (and also here in tex form https://github.com/liziscool/cas741_project/blob/master/docs/SRS/SRS.tex)

If you could review them when you get a chance that would be greatly appreciated. 

Thank you!

**Comment by smiths** [comment]
@liziscool, please create a separate issue for each reviewer.  By having separate issues, the reviewer can close the issue as they accomplish the assigned task.

**Comment by smiths** [comment]
I haven't finished the review, so we shouldn't close this issue.  :smile:

**Comment by liziscool** [comment]
My apologies!

**Comment by smiths** [comment]
No problem.  :smile:

**Comment by smiths** [comment]
I've fixed `SRS.tex` in e4f6dda so that it compiles.  Also fixed some spelling mistakes.  Did not correct Morelet versus Morlet (both are used), since I don't know which is correct.  :smile:

**Comment by smiths** [comment]
Feedback on the SRS is provided in 3f3a6d8.  Please create issues as appropriate.
