### ISSUE TITLE
SRS verification plan

### ISSUE THREAD

**Issue by muralidn** [liziscool/cas741_project#30]
@liziscool 

I believe the SRS verification plan should describe how the SRS was reviewed (verified),

![image](https://user-images.githubusercontent.com/71282513/97809214-ab9d9900-1c91-11eb-88b8-d8750a392a81.png)

![image](https://user-images.githubusercontent.com/71282513/97809259-de479180-1c91-11eb-8444-e97ccaa5b015.png)

**Comment by liziscool** [comment]
Yes, it seems I totally misinterpreted what this was supposed to communicate. Thanks :) 
It's fixed here: https://github.com/liziscool/cas741_project/commit/272a9e5e35bc819232fce462a7a971dad556b7ed
