### ISSUE TITLE
Please review MIS and MG 

### ISSUE THREAD

**Issue by liziscool** [liziscool/cas741_project#40]
Hi @smiths,
Please review my MIS and MG when you are able to :) 
https://github.com/liziscool/cas741_project/blob/master/docs/Design/MG/MG.pdf
https://github.com/liziscool/cas741_project/blob/master/docs/Design/MIS/MIS-Checklist.pdf
Thanks

**Comment by smiths** [comment]
Feedback on the MIS and MG available in 2339025.
