### ISSUE TITLE
Roadmap missing in the introduction

### ISSUE THREAD

**Issue by muralidn** [liziscool/cas741_project#6]
@liziscool 

Section 2, introduction, should include a brief introduction about the problem domain followed by a roadmap paragraph.

![image](https://user-images.githubusercontent.com/71282513/95847318-2f86f400-0d6a-11eb-9fb3-387cd72a8a87.png)

**Comment by liziscool** [comment]
@muralidn thank you, I read this as the same thing as the 'Organization of document' subsection but I see now they are different things.
