### ISSUE TITLE
Question - User and Intended reader characteristics 

### ISSUE THREAD

**Issue by muralidn** [liziscool/cas741_project#8]
@liziscool 

The characteristics of the user and the intended reader are the same, is that intentional? In other words. are the end-users of the documents only the designers of the SRS?

**Comment by liziscool** [comment]
Yes, I think so. Since I plan to incorporate this program into a larger framework I am using for my research the end-user is mainly just me (and my supervisor and the other student on this project). Good question though, Thank you!
