### ISSUE TITLE
System context introductory paragraph

### ISSUE THREAD

**Issue by muralidn** [liziscool/cas741_project#9]
@liziscool 
The introductory paragraph of the system context contains user responsibilities. I believe the purpose of this paragraph is to set the context for the block diagram, that is, what does the circle/square represent, and does the application require any external interfaces,

![image](https://user-images.githubusercontent.com/71282513/95898943-6b8f7880-0dad-11eb-91b6-ffe362675846.png)

**Comment by liziscool** [comment]
I believe you are correct, thank you.
